
postgres: &postgres
  adapter: postgresql
  host: localhost
  username: azurely
  password: blocio

development:
  <<: *postgres
  database: edict2_development

test:
  <<: *postgres
  database: edict2_test

production:
  <<: *postgres
  database: edict2_production
